theme: jekyll-theme-minimal
title: Daniel Del Toro Devias Homepage
description: I went to Archbishop Molloy High School in Briarwood Queens, New York. I grew up nearby in Jamaica Queens, New York. I like to be fit, play video games, and vibe code in my free time. I have also recently taken up Tango with RITs Tango Club and have gotten pretty good at it.  
